"""update

Revision ID: f84f74a0bb61
Revises: d398c46d1a90
Create Date: 2023-10-06 00:46:33.624986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84f74a0bb61'
down_revision = 'd398c46d1a90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app', 'usrname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('usrname', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
